const $=s=>document.querySelector(s),roundExcel=n=>n<0?-Math.round(-n):Math.round(n),yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(roundExcel(n||0)),pts=n=>new Intl.NumberFormat('ja-JP').format(roundExcel(n||0)),signedPts=n=>`${n>0?'+':''}${pts(n)} pt`;
const rateByTerm={84:1.79,72:1.96,60:2.28,48:2.75,36:3.45},daibenRateByTerm={84:1.60,72:1.80,60:2.00,48:2.50,36:3.20};
let catalog,state={category:'hyper',lines:[],extras:[],salesPrice:0,manualSales:false};
const fields=['leaseCompany','tradeInType','deposit','advance','serviceSale','targetMonthly','daibenRate','oldMonthly1','oldMonths1','oldMonthly2','oldMonths2'];
async function init(){catalog=await fetch('catalog.json').then(r=>r.json());const saved=localStorage.getItem('sales-calculator-v2');if(saved){try{state={...state,...JSON.parse(saved)}}catch{}}hydrateState();renderCategories();bind();selectCategory(state.category,false);restoreFields();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');}
function hydrateState(){const products=current().products;state.lines=state.lines.map(line=>{const fresh=products.find(product=>product.id===line.id);return fresh?{...fresh,qty:line.qty}:line});state.lines.forEach(line=>{(line.includedExtras||[]).forEach(extra=>{const id=`${line.id}::${extra.id}`;if(!state.extras.some(item=>item.id===id))state.extras.push({...extra,id,name:`${extra.name}（商品付属）`,qty:line.qty,autoIncluded:true})})})}
function bind(){$('#productSearch').addEventListener('input',renderProducts);$('#productSelect').addEventListener('change',()=>{renderProductMeta();renderExtrasSelect()});$('#maintenanceSelect').addEventListener('change',renderMaintenanceMeta);$('#addProduct').onclick=addProduct;$('#addExtra').onclick=addExtra;$('#addMaintenance').onclick=addMaintenance;$('#resetBtn').onclick=()=>{if(confirm('入力内容をすべてリセットしますか？')){localStorage.removeItem('sales-calculator-v2');location.reload()}};$('#salesPrice').addEventListener('input',e=>{state.salesPrice=+e.target.value||0;state.manualSales=true;renderTotals()});$('#contractType').addEventListener('change',renderTotals);$('#calculationMode').addEventListener('change',e=>{if(e.target.value==='leaseToSales'&&!(+$('#targetMonthly').value))$('#targetMonthly').value=Math.floor((state.salesPrice*(+$('#leaseRate').value||0)/100)/100)*100;renderTotals()});$('#daibenMode').addEventListener('change',renderTotals);$('#leaseTerm').addEventListener('change',e=>{$('#leaseRate').value=rateByTerm[e.target.value]??2.28;$('#daibenRate').value=daibenRateByTerm[e.target.value]??2;renderTotals()});$('#leaseRate').addEventListener('input',renderTotals);fields.forEach(id=>$('#'+id).addEventListener('input',renderTotals));}
function current(){return catalog.categories.find(c=>c.key===state.category)||catalog.categories[0]}
function renderCategories(){$('#categories').innerHTML=catalog.categories.map(c=>`<button type="button" class="category-button ${c.key===state.category?'active':''}" data-key="${c.key}">${c.label}</button>`).join('');$('#categories').onclick=e=>{const b=e.target.closest('button');if(b)selectCategory(b.dataset.key,true)}}
function selectCategory(key,clear){state.category=key;if(clear){state.lines=[];state.extras=[];state.manualSales=false;state.salesPrice=0}renderCategories();$('#contractType').value=key==='hyper-cash'?'cash':'lease';$('#productSearch').value='';renderProducts();renderExtrasSelect();renderMaintenanceSelect();render();}
function filteredProducts(){const q=$('#productSearch').value.trim().toLowerCase();return current().products.filter(p=>!q||`${p.name} ${p.model} ${p.code} ${p.group}`.toLowerCase().includes(q)).slice(0,200)}
function renderProducts(){const list=filteredProducts();$('#productCount').textContent=`${current().products.length}商品`;$('#productSelect').innerHTML=list.length?list.map(p=>`<option value="${p.id}">${p.group?`[${p.group}] `:''}${p.name}</option>`).join(''):'<option value="">該当なし</option>';renderProductMeta()}
function renderProductMeta(){const p=current().products.find(x=>x.id===$('#productSelect').value);$('#productMeta').textContent=p?`${p.model||p.code} ｜ 基準価格 ${yen(p.price)}${p.basePoints!=null?` ｜ 基準 ${pts(p.basePoints)}pt`:p.leasePoints!=null?` ｜ リース ${pts(p.leasePoints)}pt`:''}`:''}
function renderExtrasSelect(){const product=current().products.find(x=>x.id===$('#productSelect').value),family=product&&(/^FG/.test(product.name)||/^Y9FG/.test(product.code))?'FG':'IG',xs=(current().extras||[]).filter(x=>!x.appliesTo||x.appliesTo===family);$('#extraSelect').innerHTML=xs.length?xs.map(x=>`<option value="${x.id}">[${x.group}] ${x.name}（${yen(x.price)}）</option>`).join(''):'<option value="">追加項目なし</option>'}
function renderMaintenanceSelect(){const xs=current().maintenance||[],select=$('#maintenanceSelect'),button=$('#addMaintenance');select.innerHTML=xs.length?xs.map(x=>`<option value="${x.id}">${x.name}（${yen(x.price)}・${pts(x.points||0)}pt）</option>`).join(''):'<option value="">選択できる保守なし</option>';select.disabled=!xs.length;button.disabled=!xs.length;renderMaintenanceMeta()}
function renderMaintenanceMeta(){const x=(current().maintenance||[]).find(i=>i.id===$('#maintenanceSelect').value);$('#maintenanceMeta').textContent=x?`${x.code||'コードなし'} ｜ 金額 ${yen(x.price)} ｜ ${pts(x.points||0)}pt${x.maintenanceCount?` ｜ 保守カウント ${yen(x.maintenanceCount)}`:''}`:'このカテゴリは保守契約が商品に含まれるか、選択対象がありません。'}
function addIncludedExtras(product,delta){(product.includedExtras||[]).forEach(extra=>{const id=`${product.id}::${extra.id}`,old=state.extras.find(x=>x.id===id);if(old){old.qty+=delta;if(old.qty<=0)state.extras=state.extras.filter(x=>x.id!==id)}else if(delta>0)state.extras.push({...extra,id,name:`${extra.name}（商品付属）`,qty:delta,autoIncluded:true})})}
function addProduct(){const p=current().products.find(x=>x.id===$('#productSelect').value);if(!p)return;const old=state.lines.find(x=>x.id===p.id);old?old.qty++:state.lines.push({...p,qty:1});addIncludedExtras(p,1);syncAutoSales();render()}
function addExtra(){const x=(current().extras||[]).find(x=>x.id===$('#extraSelect').value);if(!x)return;const old=state.extras.find(i=>i.id===x.id);old?old.qty++:state.extras.push({...x,qty:1});render()}
function addMaintenance(){const x=(current().maintenance||[]).find(x=>x.id===$('#maintenanceSelect').value);if(!x)return;const old=state.extras.find(i=>i.id===x.id);old?old.qty++:state.extras.push({...x,qty:1});render()}
function changeQty(kind,id,delta){const list=state[kind],item=list.find(x=>x.id===id);if(!item)return;const before=item.qty,after=Math.max(0,before+delta),applied=after-before;item.qty=after;if(item.qty<=0)state[kind]=list.filter(x=>x.id!==id);if(kind==='lines'){addIncludedExtras(item,applied);syncAutoSales()}render()}
function syncAutoSales(){if(!state.manualSales&&$('#calculationMode').value==='salesToLease')state.salesPrice=state.lines.reduce((s,x)=>s+x.price*x.qty,0)+state.extras.filter(x=>x.autoIncluded).reduce((s,x)=>s+x.price*x.qty,0)}
function renderLines(kind,sel){const list=state[kind];$(sel).innerHTML=list.map(x=>`<div class="line-item"><div><div class="line-title">${x.name}</div><div class="line-sub">${x.model||x.code||x.group} ｜ ${yen(x.price*x.qty)}</div></div><div class="qty"><button type="button" aria-label="減らす" data-action="-">−</button><strong>${x.qty}</strong><button type="button" aria-label="増やす" data-action="+">＋</button><button type="button" class="remove" aria-label="削除" data-action="x">×</button></div></div>`).join('');$(sel).onclick=e=>{const row=e.target.closest('.line-item'),btn=e.target.closest('button');if(!row||!btn)return;const i=[...$(sel).children].indexOf(row),id=state[kind][i].id;changeQty(kind,id,btn.dataset.action==='+'?1:btn.dataset.action==='-'?-1:-999)}}
function applyTradeInPoints(points){const type=$('#tradeInType').value;if(type==='own')return points+5;if(type==='own3')return points+3;if(type==='other')return roundExcel((points+10)*1.2);return points}
function calcOperatingSales(){return state.salesPrice+(+$('#deposit').value||0)-(+$('#serviceSale').value||0)-(+$('#advance').value||0)}
function calcBodyAmount(){const extrasAmount=state.extras.reduce((s,x)=>s+x.price*x.qty,0),otherBodies=state.lines.slice(1).reduce((s,x)=>s+x.price*x.qty,0);return calcOperatingSales()-extrasAmount-otherBodies}
function calcPointBreakdown(){const c=current(),extraPoints=state.extras.reduce((s,x)=>s+(x.points||0)*x.qty,0);let bodyPoints=0;if(c.mode==='line'){const type=$('#contractType').value;bodyPoints=state.lines.reduce((s,x)=>s+(type==='cash'?x.cashPoints:x.leasePoints)*x.qty,0)}else if(state.lines.length){const main=state.lines[0],mainQty=main.qty||1,bodyAmount=calcBodyAmount(),mainPoints=roundExcel((main.basePoints||0)*mainQty-((main.basePrice*mainQty-bodyAmount)/(main.step||1))),other=state.lines.slice(1).reduce((s,x)=>s+roundExcel((x.basePoints||0)*x.qty-((x.basePrice*x.qty-x.price*x.qty)/(x.step||1))),0);bodyPoints=mainPoints+other}const beforeTrade=bodyPoints+extraPoints,finalPoints=applyTradeInPoints(beforeTrade);return{bodyPoints,extraPoints,tradePoints:finalPoints-beforeTrade,finalPoints}}
function calcPoints(){return calcPointBreakdown().finalPoints}
function calcDaiben(){const mode=$('#daibenMode').value,rate=(+$('#daibenRate').value||0)/100;let oldTotal=0,d1=0,d2=0;[1,2].forEach(i=>{const base=(+$('#oldMonthly'+i).value||0)*(+$('#oldMonths'+i).value||0),eligible=mode==='levelup'?base*1.1:base,value=mode==='none'?0:eligible*rate;oldTotal+=mode==='none'?0:eligible;if(i===1)d1=value;else d2=value});return{mode,oldTotal,d1,d2,total:d1+d2}}
function renderTotals(){const subtotal=[...state.lines,...state.extras].reduce((s,x)=>s+x.price*x.qty,0),productSubtotal=state.lines.reduce((s,x)=>s+x.price*x.qty,0)+state.extras.filter(x=>x.autoIncluded).reduce((s,x)=>s+x.price*x.qty,0),contract=$('#contractType').value,mode=$('#calculationMode').value,rate=+$('#leaseRate').value||0,d=calcDaiben();if(mode==='leaseToSales'&&contract==='lease'){const target=+$('#targetMonthly').value||0,salesBase=rate>0?Math.max(0,target-d.total)/(rate/100):0;state.salesPrice=Math.floor((salesBase+1e-7)/100)*100;state.manualSales=true}else if(!state.manualSales&&state.salesPrice!==productSubtotal)state.salesPrice=productSubtotal;$('#salesPrice').value=Math.round(state.salesPrice);$('#salesPrice').readOnly=mode==='leaseToSales'&&contract==='lease';const operatingSales=calcOperatingSales(),monthly=mode==='leaseToSales'&&contract==='lease'?(+$('#targetMonthly').value||0):Math.floor((Math.max(0,operatingSales)*rate/100+d.total)/100)*100,pointBreakdown=calcPointBreakdown(),points=pointBreakdown.finalPoints,bodyAmount=calcBodyAmount();$('#subtotal').textContent=yen(subtotal);$('#bodyAmount').textContent=yen(bodyAmount);$('#netPayment').textContent=yen(operatingSales);$('#bodyPoints').textContent=signedPts(pointBreakdown.bodyPoints);$('#extraPoints').textContent=signedPts(pointBreakdown.extraPoints);$('#tradePoints').textContent=signedPts(pointBreakdown.tradePoints);$('#oldCancelTotal').textContent=yen(d.oldTotal);$('#daiben1').textContent=yen(d.d1);$('#daiben2').textContent=yen(d.d2);$('#daibenTotal').textContent=yen(d.total);$('#monthlyLease').textContent=yen(monthly);$('#totalPoints').textContent=pts(points);$('#resultPoints').textContent=`${pts(points)} pt`;$('#heroSales').textContent=yen(operatingSales);$('#bodyAmountRow').classList.toggle('hidden',current().mode==='line');$('#companyField').classList.toggle('hidden',contract==='cash');$('#monthlyInputField').classList.toggle('hidden',contract==='cash');$('#directionField').classList.toggle('hidden',contract==='cash');$('#daibenRow').classList.toggle('hidden',contract==='cash'||d.mode==='none');$('#monthlyRow').classList.toggle('hidden',contract==='cash');$('#termField').classList.toggle('hidden',contract==='cash');$('#rateField').classList.toggle('hidden',contract==='cash');$('#daibenPanel').classList.toggle('hidden',contract==='cash');save()}
function render(){$('#linesSection').classList.toggle('hidden',!state.lines.length);renderLines('lines','#lines');renderLines('extras','#extras');renderTotals()}
function restoreFields(){if(state.form){fields.forEach(id=>{if(state.form[id]!=null)$('#'+id).value=state.form[id]});$('#contractType').value=state.form.contractType||$('#contractType').value;$('#calculationMode').value=state.form.calculationMode||'salesToLease';$('#leaseTerm').value=state.form.leaseTerm||60;$('#leaseRate').value=state.form.leaseRate||2.28;const savedMode=state.form.daibenMode||'none';$('#daibenMode').value=savedMode==='simple'?'simple':savedMode==='none'?'none':'levelup'}}
function save(){state.form={contractType:$('#contractType').value,calculationMode:$('#calculationMode').value,leaseTerm:$('#leaseTerm').value,leaseRate:$('#leaseRate').value,daibenMode:$('#daibenMode').value,...Object.fromEntries(fields.map(id=>[id,$('#'+id).value]))};localStorage.setItem('sales-calculator-v2',JSON.stringify(state))}
init();
